node {
    notify("Started")
    
    try {
        stage("checkout") {
            //git "https://github.com/mrgaurav00/jenkins-sonarqube-samples.git"
			checkout scm
        }
        
        dir("sample-msbuild-project") {
            def scannerHome = tool "MSBuild Installation";
            stage("build") {
                withSonarQubeEnv("Sonarqube Server") {
					bat "${scannerHome}\\SonarScanner.MSBuild.exe begin /k:\"org.sonarqube:sonarqube-scanner-msbuild\" /n:\"Example of MSBuild project\" /v:\"1.0\""
					bat "MSBuild.exe SomeConsoleApplication.sln /t:Rebuild"
					bat "${scannerHome}\\SonarScanner.MSBuild.exe end"
                }
            }
            
            //stage("archival") {
            //    archiveArtifacts "target/*.?ar"
            //}
        }
        
        notify("Success")
    } catch (err) {
        notify("Error ${err}")
        currentBuild.result = "FAILURE"
    }
}

def notify(status) {
    emailext(
        to: "mrgaurav00@trash-mail.com", 
        subject: "${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
        body: "<p>${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p><p>Check console output at '${BUILD_URL}' to view the results."
    )
}